"""Add already_emailed column to shift preferences

Revision ID: d67b3f8faabd
Revises: 
Create Date: 2025-08-26 20:52:22.550295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67b3f8faabd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('already_emailed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_preferences', schema=None) as batch_op:
        batch_op.drop_column('already_emailed')

    # ### end Alembic commands ###
